Homework week 1

The goal of this coding project is to get you up and running with
emacs and python, including
- interactive python code execution in emacs.
- reading CSV data into python as a DataFrame.
- printing a summary of the number of rows/columns in a DataFrame.

You will need to follow the [[file:../installation.org][installation instructions]] to get emacs
working with interactive python execution on your computer.

** Part 1: reading CSV data

Your goal is to write a python script that performs the following steps:

1. use urllib.request.urlretrieve to programmatically download a copy
   of the zip.test data set from
   [[file:../data/zip.test.gz]]
   (original was from
   https://web.stanford.edu/~hastie/ElemStatLearn/datasets/zip.test.gz
   but is now broken).  Use an if statement so that the download only
   happens if the file does not yet exist on your system. Make sure
   the saved file has the gz suffix, which indicates that the file has
   been compressed using gzip. This data file represents images of
   handwritten digits, one example per line/row. Each example is one
   of the ten possible digits (as indicated by the label in the first
   column).
2. Use pandas.read_csv to read the compressed CSV data file into
   python as a DataFrame (you may need to use sep/header arguments to
   parse the CSV correctly). Print the shape attribute which should be
   a tuple of integers: (rows,columns).
3. Take a screenshot of your emacs window, split in two, with your
   code in the top window, and the python console (with output) on the
   bottom.
   
For your homework please upload in bblearn a single PDF file, with (1)
your python code, (2) the corresponding results/output (after running
your python code), and (3) your commentary/interpretation/answers to
questions.

